class TourismPlace {
  String name;
  String location;
  String description;
  String openDays;
  String openTime;
  String ticketPrice;
  String player;
  String imageAsset;
  List<String> imageUrls;
  List<String> players;

  TourismPlace({
    required this.name,
    required this.location,
    required this.description,
    required this.openDays,
    required this.openTime,
    required this.ticketPrice,
    required this.player,
    required this.imageAsset,
    required this.imageUrls,
    required this.players,
  });
}

var tourismPlaceList = [
  TourismPlace(
    name: 'The Bernabéu',
    location: 'Madird, Spain',
    description:
        'Berlokasi di jantung kota Madrid, Stadion Bernabéu menjadi sebuah katedral sepak bola yang tak pernah kehilangan magisnya. Selain karena menjadi kandang ikonik Real Madrid, arena ini juga menghadirkan sejarah panjang kejayaan Eropa. Semua itu kini dibalut dalam renovasi futuristik berteknologi tinggi.',
    openDays: 'Everyday',
    openTime: '10:00 - 18:30',
    ticketPrice: 'Rp 677000',
    player: '22 Player',
    imageAsset: 'images/real-madrid2.jpeg',
    imageUrls: [
      'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/17/a2/f4/16/stadio-santiago-bernabeu.jpg?w=1000&h=-1&s=1',
      'https://pbs.twimg.com/media/G4NCFWNWEAAcpmB?format=jpg&name=medium',
      'https://pbs.twimg.com/media/G4CuTU3WQAALRWb?format=jpg&name=large',
      'https://pbs.twimg.com/media/G31I1mXXAAAlW-d?format=jpg&name=4096x4096',
    ],
    players: [
      'Thibaut Courtois',
      'Andriy Lunin',
      'Dani Carvajal',
      'Éder Militão',
      'David Alaba',
      'Jude Bellingham',
      'Eduardo Camavinga',
      'Vinícius Júnior',
      'Federico Valverde',
      'Kylian Mbappé',
      'Luka Modrić',
      'Rodrygo Goes',
      'Aurélien Tchouaméni',
      'Arda Güler',
      'Endrick',
      'Trent Alexander-Arnold',
      'Jesús Vallejo',
      'Dani Ceballos',
      'Fran García',
      'Brahim Díaz',
      'Antonio Rüdiger',
      'Ferland Mendy',
    ],
  ),
  TourismPlace(
    name: 'Spotify Camp Nou',
    location: 'Catalunya, Spain',
    description:
        'Spotify Camp Nou Terletak di distrik Les Corts Barcelona, Spotify Camp Nou adalah stadion terbesar yang ada di Eropa. Selain karena menjadi simbol kebanggaan FC Barcelona, arena ini juga telah menyaksikan lahirnya filosofi "tiki-taka". Semua itu membuatnya menjadi destinasi wajib bagi para penggemar sepak bola global.',
    openDays: 'Everyday',
    openTime: '10:00 - 18:00',
    ticketPrice: 'Rp 541000',
    player: '22 Player',
    imageAsset: 'images/barca3.jpg',
    imageUrls: [
      'https://pbs.twimg.com/media/G5YvYOrb0AAIv7y?format=jpg&name=medium',
      'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/0f/2d/9c/a1/camp-nou.jpg?w=1000&h=-1&s=1',
      'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/26/50/28/e4/spotify-camp-nou.jpg?w=1000&h=-1&s=1',
      'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1a/39/41/99/visite-du-camp-nou-barcelone.jpg?w=1000&h=-1&s=1',
    ],
    players: [
      'Marc-André ter Stegen',
      'Pau Cubarsí',
      'Alejandro Balde',
      'Ronald Araújo',
      'Iñigo Martínez',
      'Gavi',
      'Ferran Torres',
      'Pedri',
      'Robert Lewandowski',
      'Ansu Fati',
      'Raphinha',
      'Iñaki Peña',
      'Pablo Torre',
      'Fermín López',
      'Marc Casadó',
      'Pau Víctor',
      'Lamine Yamal',
      'Dani Olmo',
      'Frenkie de Jong',
      'Jules Koundé',
      'Andreas Christensen',
      'Eric García',
      'Wojciech Szczęsny',
      'Héctor Fort',
      'Gerard Martín',
    ],
  ),
  TourismPlace(
    name: 'Anfield',
    location: 'Liverpool, England',
    description:
        'Anfield Berdiri kokoh di kota Liverpool, Anfield menjadi markas yang angker bagi setiap lawan. Selain karena atmosfer magis dari "The Kop", stadion ini juga menghadirkan sejarah emosional yang mendalam. Semua itu terangkum sempurna dalam nyanyian "You ll Never Walk Alone" sebelum laga.',
    openDays: 'Tuesday - Saturday',
    openTime: '09:00 - 14:30',
    ticketPrice: 'Rp 20000',
    player: '22 Player',
    imageAsset: 'images/ipul1.jpg',
    imageUrls: [
      'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1b/f8/f2/c7/photo1jpg.jpg?w=1000&h=-1&s=1',
      'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1c/0c/52/a9/anfield-stadium.jpg?w=1000&h=-1&s=1',
      'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1c/0e/5a/a4/the-kop.jpg?w=1000&h=-1&s=1',
      'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1b/ef/f7/f3/photo8jpg.jpg?w=1000&h=-1&s=1',
    ],
    players: [
      'Alisson Becker',
      'Caoimhín Kelleher',
      'Vítězslav Jaroš',
      'Virgil van Dijk',
      'Ibrahima Konaté',
      'Jarell Quansah',
      'Joe Gomez',
      'Andrew Robertson',
      'Kostas Tsimikas',
      'Alexander Isak',
      'Conor Bradley',
      'Alexis Mac Allister',
      'Dominik Szoboszlai',
      'Ryan Gravenberch',
      'Curtis Jones',
      'Wataru Endō',
      'Harvey Elliott',
      'Tyler Morton',
      'Trey Nyoni',
      'Mohamed Salah',
      'Luis Díaz',
      'Diogo Jota',
      'Darwin Núñez',
      'Cody Gakpo',
      'Federico Chiesa',
    ],
  ),
  TourismPlace(
    name: 'Old Trafford',
    location: 'Manchester, England',
    description:
        'Old Trafford Menjulang di kawasan Manchester, Old Trafford menjadi panggung impian yang legendaris. Selain karena statusnya sebagai rumah Manchester United, tempat ini juga telah melahirkan begitu banyak bintang di era modern. Semua itu menjadikannya sebagai "Theatre of Dreams" yang sesungguhnya bagi fans.',
    openDays: 'Tuesday - Saturday',
    openTime: '09:00 - 14:30',
    ticketPrice: 'Rp 20000',
    player: '22 Player',
    imageAsset: 'images/mu1.jpg',
    imageUrls: [
      'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/0e/60/75/3d/old-trafford-featuring.jpg?w=1000&h=-1&s=1',
      'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/09/c0/50/4f/manchester-united-museum.jpg?w=1000&h=-1&s=1',
      'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/31/84/c2/87/caption.jpg?w=1000&h=-1&s=1',
      'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/10/0e/ba/5d/photo3jpg.jpg?w=1000&h=-1&s=1',
    ],
    players: [
      'André Onana',
      'Altay Bayindir',
      'Tom Heaton',
      'Diogo Dalot',
      'Noussair Mazraoui',
      'Matthijs de Ligt',
      'Lisandro Martínez',
      'Harry Maguire',
      'Victor Lindelöf',
      'Jonny Evans',
      'Leny Yoro',
      'Luke Shaw',
      'Tyrell Malacia',
      'Casemiro',
      'Manuel Ugarte',
      'Kobbie Mainoo',
      'Christian Eriksen',
      'Mason Mount',
      'Bruno Fernandes',
      'Toby Collyer',
      'Marcus Rashford',
      'Alejandro Garnacho',
      'Amad Diallo',
      'Antony',
      'Rasmus Højlund',
      'Joshua Zirkzee',
    ],
  ),
  TourismPlace(
    name: 'Etihad Stadium',
    location: 'Manchester, England',
    description:
        'Etihad Stadium Berada di jantung kawasan Eastlands, Etihad Stadium menjadi simbol era baru kekuatan Manchester. Selain karena menjadi kandang Manchester City yang dominan, arena ini juga menghadirkan fasilitas ultra-modern. Semua itu mencerminkan ambisi klub yang kini disegani di kancah Eropa.',
    openDays: 'Everyday',
    openTime: '24 hours',
    ticketPrice: 'Free',
    player: '22 Player',
    imageAsset: 'images/city1.jpg',
    imageUrls: [
      'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/09/cb/d1/52/etihad-stadium-exterior.jpg?w=800&h=-1&s=1',
      'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/31/82/28/13/caption.jpg?w=1000&h=-1&s=1',
      'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/0a/ed/35/54/manchester-city-football.jpg?w=1000&h=-1&s=1',
      'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1d/6e/18/0f/etihad-stadium.jpg?w=1000&h=-1&s=1',
    ],
    players: [
      'Ederson',
      'Stefan Ortega',
      'Rúben Dias',
      'Joško Gvardiol',
      'Manuel Akanji',
      'John Stones',
      'Nathan Aké',
      'Rico Lewis',
      'Kyle Walker',
      'Rodri',
      'Kevin De Bruyne',
      'Phil Foden',
      'Bernardo Silva',
      'Mateo Kovačić',
      'Matheus Nunes',
      'Ilkay Gündoğan',
      'James McAtee',
      'Claudio Echeverri',
      'Erling Haaland',
      'Jérémy Doku',
      'Jack Grealish',
      'Savinho',
      'Oscar Bobb',
    ],
  ),
  TourismPlace(
    name: 'Emirates Stadium',
    location: 'London, England',
    description:
        'Emirates Stadium Berdiri megah di London Utara, Emirates Stadium adalah salah satu arena termodern di Inggris. Selain karena menggantikan Highbury yang bersejarah, stadion ini juga menghadirkan kenyamanan dan visibilitas terbaik. Semua itu dirancang untuk mendukung gaya permainan indah yang diusung Arsenal.',
    openDays: 'Everyday',
    openTime: '24 hours',
    ticketPrice: 'Free',
    player: '22 Player',
    imageAsset: 'images/arsenal1.jpg',
    imageUrls: [
      'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/31/53/56/e1/full-view.jpg?w=1000&h=-1&s=1',
      'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/0f/79/da/57/photo6jpg.jpg?w=1000&h=-1&s=1',
      'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/31/53/53/bb/henry-s-statue.jpg?w=1000&h=-1&s=1',
      'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/17/9b/26/3d/photo1jpg.jpg?w=1000&h=-1&s=1',
    ],
    players: [
      'David Raya',
      'William Saliba',
      'Gabriel Magalhães',
      'Jurrien Timber',
      'Riccardo Calafiori',
      'Ben White',
      'Declan Rice',
      'Mikel Merino',
      'Martin Ødegaard',
      'Bukayo Saka',
      'Gabriel Martinelli',
      'Kai Havertz',
      'Gabriel Jesus',
      'Raheem Sterling',
      'Ethan Nwaneri',
    ],
  ),
  TourismPlace(
    name: 'Stamford Bridge',
    location: 'London, England',
    description:
        'Stamford Bridge Terletak di kawasan elite Fulham, Stamford Bridge menjadi benteng biru yang sulit ditaklukkan. Selain karena menjadi rumah bagi Chelsea FC, stadion ini juga memiliki karakter unik yang padat dan intim. Semua itu menciptakan atmosfer elektrik yang didorong oleh loyalitas fans "The Blues".',
    openDays: 'Everyday',
    openTime: '06:00 - 17:00',
    ticketPrice: 'Rp 3000',
    player: '22 Player',
    imageAsset: 'images/celsi3.jpg',
    imageUrls: [
      'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/30/eb/cb/a2/caption.jpg?w=1000&h=-1&s=1',
      'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/30/e8/18/24/caption.jpg?w=1000&h=-1&s=1',
      'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/30/e8/18/21/caption.jpg?w=1000&h=-1&s=1',
      'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/30/e8/18/1d/caption.jpg?w=1000&h=-1&s=1',
      'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/30/cc/b3/1c/caption.jpg?w=1000&h=-1&s=1',
    ],
    players: [
      'Robert Sánchez',
      'Filip Jørgensen',
      'Reece James',
      'Malo Gusto',
      'Levi Colwill',
      'Wesley Fofana',
      'Moisés Caicedo',
      'Enzo Fernández',
      'Romeo Lavia',
      'Cole Palmer',
      'Christopher Nkunku',
      'Nicolas Jackson',
      'Pedro Neto',
      'João Félix',
      'Jadon Sancho',
      'Estêvão Willian',
      'Kendry Páez',
    ],
  ),
  TourismPlace(
    name: 'Tottenham Hotspur Stadium',
    location: 'Tottenham, England',
    description:
        'Tottenham Hotspur Stadium Menjadi tengara baru di London Utara, Tottenham Hotspur Stadium adalah tolok ukur arena masa depan. Selain karena arsitekturnya yang memukau, stadion ini juga menghadirkan teknologi lapangan "retractable" pertama. Semua itu dirancang untuk memberi pengalaman multi-fungsi, dari bola hingga konser NFL.',
    openDays: 'Everyday',
    openTime: '24 hours',
    ticketPrice: 'Free',
    player: '22 Player',
    imageAsset: 'images/tenham2.jpg',
    imageUrls: [
      'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1b/1f/bc/b3/tottenham-hotspur-stadium.jpg?w=1000&h=-1&s=1',
      'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/17/1d/f6/d5/photo0jpg.jpg?w=1000&h=-1&s=1',
      'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/30/f7/62/e0/caption.jpg?w=1000&h=-1&s=1',
      'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/30/9b/8c/66/caption.jpg?w=1000&h=-1&s=1',
    ],
    players: [
      'Guglielmo Vicario',
      'Pedro Porro',
      'Micky van de Ven',
      'Cristian Romero',
      'Destiny Udogie',
      'James Maddison',
      'Pape Matar Sarr',
      'Yves Bissouma',
      'Dejan Kulusevski',
      'Son Heung-min',
      'Dominic Solanke',
      'Brennan Johnson',
      'Lucas Bergvall',
      'Archie Gray',
      'Yang Min-hyeok',
    ],
  ),
  TourismPlace(
    name: 'San Siro',
    location: 'Milan, Italy',
    description:
        'San Siro Berdiri sebagai ikon kota Milan, San Siro menjadi rumah legendaris bagi dua rival abadi. Selain karena digunakan bersama oleh AC Milan dan Inter Milan, arena ini juga menghadirkan struktur spiralnya yang khas. Semua itu menjadikannya salah satu stadion paling dikenal dalam sejarah sepak bola Italia.',
    openDays: 'Everyday',
    openTime: '24 hours',
    ticketPrice: 'Free',
    player: '22 Player',
    imageAsset: 'images/milan3.jpg',
    imageUrls: [
      'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/2b/ee/64/75/caption.jpg?w=1000&h=-1&s=1',
      'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/2b/ee/64/73/caption.jpg?w=1000&h=-1&s=1',
      'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/11/1e/59/e1/photo0jpg.jpg?w=1000&h=-1&s=1',
      'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/11/1d/29/b0/photo5jpg.jpg?w=800&h=-1&s=1',
    ],
    players: [
      'Mike Maignan',
      'Theo Hernández',
      'Fikayo Tomori',
      'Strahinja Pavlović',
      'Emerson Royal',
      'Tijjani Reijnders',
      'Youssouf Fofana',
      'Christian Pulisic',
      'Rafael Leão',
      'Álvaro Morata',
      'Tammy Abraham',
      'Samuel Chukwueze',
      'Francesco Camarda',
    ],
  ),
  TourismPlace(
    name: 'San Paolo Stadio',
    location: 'Naples, Italy',
    description:
        'San Paolo Stadium (Stadio Diego Armando Maradona) Bersemayam di kota Naples, San Paolo adalah kuil bagi para pemuja sang legenda. Selain karena menjadi saksi kehebatan Diego Maradona, stadion ini juga menghadirkan atmosfer paling berapi-api di Italia. Semua itu didorong oleh kecintaan fans Napoli yang nyaris menyerupai sebuah agama.',
    openDays: 'Saturday - Thursday',
    openTime: '09:00 - 15:30',
    ticketPrice: 'Rp 3000',
    player: '22 Player',
    imageAsset: 'images/napol1.jpg',
    imageUrls: [
      'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/2e/01/65/e1/estadio-en-proceso-de.jpg?w=1000&h=-1&s=1',
      'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/2b/ad/f9/32/museo-el-templo-del-futbol.jpg?w=1000&h=-1&s=1',
      'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/03/fb/f0/a4/stadio-san-paolo.jpg?w=1000&h=-1&s=1',
      'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/30/e3/b3/50/caption.jpg?w=1000&h=-1&s=1',
    ],
    players: [
      'Alex Meret',
      'Alessandro Buongiorno',
      'Amir Rrahmani',
      'Giovanni Di Lorenzo',
      'Scott McTominay',
      'Billy Gilmour',
      'André-Frank Zambo Anguissa',
      'Romelu Lukaku',
      'David Neres',
      'Stanislav Lobotka',
    ],
  ),
  TourismPlace(
    name: 'Allianz Turin',
    location: 'Turin, Italy',
    description:
        'Allianz Turin (Juventus Stadium) Berlokasi di kota Turin, Allianz Stadium menjadi benteng modern kebanggaan "Si Nyonya Tua". Selain karena menjadi stadion milik Juventus sepenuhnya, arena ini juga dirancang agar suara fans terdengar paling gemuruh. Semua itu menciptakan dominasi kandang yang tak tertandingi di Serie A.',
    openDays: 'Saturday - Thursday',
    openTime: '09:00 - 15:30',
    ticketPrice: 'Rp 3000',
    player: '22 Player',
    imageAsset: 'images/jupe1.jpg',
    imageUrls: [
      'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/23/d8/5f/d2/juventus-stadium.jpg?w=1000&h=-1&s=1',
      'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/24/4b/3b/eb/caption.jpg?w=1000&h=-1&s=1',
      'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/23/d8/5f/d0/juventus-stadium.jpg?w=1000&h=-1&s=1',
      'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/23/d8/5f/cb/juventus-stadium.jpg?w=1000&h=-1&s=1',
    ],
    players: [
      'Michele Di Gregorio',
      'Gleison Bremer',
      'Pierre Kalulu',
      'Juan Cabal',
      'Teun Koopmeiners',
      'Douglas Luiz',
      'Khéphren Thuram',
      'Kenan Yildiz',
      'Dušan Vlahović',
      'Francisco Conceição',
      'Nico González',
    ],
  ),
  TourismPlace(
    name: 'Comunale G. Sinigaglia',
    location: 'Como, Italy',
    description:
        'Comunale G. Sinigaglia Terletak di tepi Danau Como yang indah, Stadion Sinigaglia menawarkan salah satu pemandangan terindah. Selain karena menjadi markas Como 1907, stadion ini juga menghadirkan arsitektur rasionalis yang unik. Semua itu berpadu menciptakan pengalaman menonton bola yang sangat indah dan tak biasa.',
    openDays: 'Everyday',
    openTime: '09:00 - 17:00',
    ticketPrice: 'Rp 20000',
    player: '22 Player',
    imageAsset: 'images/como1.jpg',
    imageUrls: [
      'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/24/56/33/59/stadio.jpg?w=1000&h=-1&s=1',
      'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/11/72/bc/02/the-stadium.jpg?w=1000&h=-1&s=1',
      'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1b/db/40/57/curva-tifosi-como-1200x600.jpg?w=1000&h=-1&s=1',
      'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/24/56/29/c2/como.jpg?w=1000&h=-1&s=1',
    ],
    players: [
      'Emil Audero',
      'Pepe Reina',
      'Alberto Dossena',
      'Sergi Roberto',
      'Máximo Perrone',
      'Nico Paz',
      'Gabriel Strefezza',
      'Patrick Cutrone',
      'Andrea Belotti',
      'Ali Jasim',
    ],
  ),
  TourismPlace(
    name: 'Olimpico Stadium',
    location: 'Rome, Italy',
    description:
        'Olimpico Stadium Berada dalam kompleks Foro Italico Roma, Stadio Olimpico adalah arena bersejarah penuh kemegahan. Selain karena menjadi kandang bagi AS Roma dan Lazio, tempat ini juga sering menjadi tuan rumah event atletik besar. Semua itu tercermin dalam adu kreativitas "Curva Nord" dan "Curva Sud".',
    openDays: 'Everyday',
    openTime: '09:00 - 17:00',
    ticketPrice: 'Rp 20000',
    player: '22 Player',
    imageAsset: 'images/roma1.jpg',
    imageUrls: [
      'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/31/73/9f/fa/caption.jpg?w=1000&h=-1&s=1',
      'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/10/70/86/74/photo0jpg.jpg?w=1000&h=-1&s=1',
      'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/10/b0/d0/a8/stadio-olimpico.jpg?w=1000&h=-1&s=1',
      'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/10/36/76/73/photo0jpg.jpg?w=1000&h=-1&s=1',
      'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/21/50/09/3c/le-giornate-vissute-in.jpg?w=1000&h=-1&s=1',
    ],
    players: [
      'Mile Svilar',
      'Gianluca Mancini',
      'Evan Ndicka',
      'Mats Hummels',
      'Lorenzo Pellegrini',
      'Manu Koné',
      'Paulo Dybala',
      'Matías Soulé',
      'Artem Dovbyk',
      'Alexis Saelemaekers',
    ],
  ),
  TourismPlace(
    name: 'Allianz Arena',
    location: 'Munich, Germany',
    description:
        'Allianz Arena Bagaikan permata di Munich, Allianz Arena adalah salah satu stadion paling inovatif di dunia. Selain karena menjadi rumah bagi Bayern Munich, arena ini juga menghadirkan fasad yang bisa berubah warna. Semua itu dirancang untuk menciptakan identitas visual yang kuat dan atmosfer yang mengintimidasi.',
    openDays: 'Everyday',
    openTime: '07:00 - 17:00',
    ticketPrice: 'Rp 15000',
    player: '22 Player',
    imageAsset: 'images/muncen1.jpg',
    imageUrls: [
      'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/01/19/8d/29/outside-view.jpg?w=1000&h=-1&s=1',
      'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/2f/3f/2d/22/caption.jpg?w=1000&h=-1&s=1',
      'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/2f/3f/2d/28/caption.jpg?w=1000&h=-1&s=1',
      'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1b/05/1f/7f/img-20200221-210502-largejpg.jpg?w=900&h=-1&s=1',
      'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1b/c7/15/c5/9.jpg?w=1000&h=-1&s=1',
    ],
    players: [
      'Manuel Neuer',
      'Dayot Upamecano',
      'Kim Min-jae',
      'Hiroki Ito',
      'Josip Stanišić',
      'Joshua Kimmich',
      'João Palhinha',
      'Aleksandar Pavlović',
      'Jamal Musiala',
      'Michael Olise',
      'Leroy Sané',
      'Harry Kane',
      'Mathys Tel',
    ],
  ),
  TourismPlace(
    name: 'Signal Iduna Park',
    location: 'Dortmund, Germany',
    description:
        'Signal Iduna Park Menjulang di kota Dortmund, Signal Iduna Park adalah surga bagi para pecinta atmosfer sejati. Selain karena menjadi kandang Borussia Dortmund, stadion ini juga menghadirkan tribun "Yellow Wall" yang legendaris. Semua itu menciptakan pemandangan lautan manusia paling masif dan menakjubkan di Eropa.',
    openDays: 'Everyday',
    openTime: '07:00 - 17:00',
    ticketPrice: 'Rp 15000',
    player: '22 Player',
    imageAsset: 'images/dotmun1.jpg',
    imageUrls: [
      'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/0e/a7/78/53/photo1jpg.jpg?w=1000&h=-1&s=1',
      'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/0e/a1/ab/8e/photo2jpg.jpg?w=1000&h=-1&s=1',
      'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/0e/a7/78/51/photo0jpg.jpg?w=1000&h=-1&s=1',
      'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/0e/a1/ab/8c/photo1jpg.jpg?w=1000&h=-1&s=1',
      'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/0e/8f/0d/69/photo1jpg.jpg?w=1000&h=-1&s=1',
    ],
    players: [
      'Gregor Kobel',
      'Nico Schlotterbeck',
      'Waldemar Anton',
      'Yan Couto',
      'Emre Can',
      'Pascal Groß',
      'Julian Brandt',
      'Marcel Sabitzer',
      'Jamie Gittens',
      'Serhou Guirassy',
      'Karim Adeyemi',
      'Maximilian Beier',
    ],
  ),
  TourismPlace(
    name: 'BayArena',
    location: 'Leverkusen, Germany',
    description:
        'BayArena Terletak di kota Leverkusen, BayArena adalah stadion yang ringkas namun sangat modern. Selain karena menjadi markas Bayer 04 Leverkusen, arena ini juga terkenal dengan atap melingkarnya yang khas. Semua itu dirancang untuk menjaga agar atmosfer pertandingan tetap intim dan dekat dengan aksi.',
    openDays: 'Everyday',
    openTime: '24 hours',
    ticketPrice: 'Rp 20000',
    player: '22 Player',
    imageAsset: 'images/leper1.jpg',
    imageUrls: [
      'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/0f/b9/66/99/bayarena.jpg?w=1000&h=-1&s=1',
      'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/12/7f/8c/3c/img-20180331-160042-largejpg.jpg?w=1000&h=-1&s=1',
      'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/2f/84/23/89/caption.jpg?w=1000&h=-1&s=1',
      'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/2f/44/b1/25/caption.jpg?w=1000&h=-1&s=1',
      'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/2f/44/b1/20/caption.jpg?w=1000&h=-1&s=1',
    ],
    players: [
      'Lukáš Hrádecký',
      'Edmond Tapsoba',
      'Jonathan Tah',
      'Piero Hincapié',
      'Jeremie Frimpong',
      'Alejandro Grimaldo',
      'Granit Xhaka',
      'Aleix García',
      'Florian Wirtz',
      'Victor Boniface',
      'Martin Terrier',
    ],
  ),
  TourismPlace(
    name: 'Gelora Sriwijaya',
    location: 'Palembang, Indonesia',
    description:
        'Gelora Sriwijaya Jakabaring Berdiri megah di Palembang, Gelora Sriwijaya Jakabaring adalah salah satu stadion termegah di Indonesia. Selain karena menjadi kebanggaan warga Sumatera Selatan, kawasan ini juga merupakan kompleks olahraga berstandar internasional. Semua itu terbukti saat menjadi tuan rumah yang sukses untuk ajang Asian Games.',
    openDays: 'Everyday',
    openTime: '24 hours',
    ticketPrice: 'Rp 20000',
    player: '22 Player',
    imageAsset: 'images/jakabaring1.jpg',
    imageUrls: [
      'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/0c/ab/f3/d4/jakabaring.jpg?w=1000&h=-1&s=1',
      'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/0c/ab/f1/84/jakabaring.jpg?w=1000&h=-1&s=1',
      'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/0c/96/44/f8/photo2jpg.jpg?w=1000&h=-1&s=1',
      'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/0a/dc/dc/c7/jakabaring-sports-complex.jpg?w=1000&h=-1&s=1',
      'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/0c/ab/f0/0d/jakabaring.jpg?w=1000&h=-1&s=1',
      'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/0b/74/c4/59/jakabaring-sport-complex.jpg?w=1000&h=-1&s=1',
    ],
    players: [
      'Panggih Triatmojo',
      'Gabriel Silva',
      'Ragil Dimas',
      'Muhammad Rifaldi',
      'Manda Cingi',
      'Tomi Darmawan',
      'Chencho Gyeltshen',
      'Meghon Valpoort',
      'Beni Oktovianto',
    ],
  ),
];
